version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    groups:
      github-actions:
        patterns: ["*"]
    labels: [dependencies, github-actions]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Sao_Paulo
    groups:
      npm-development:
        dependency-type: development
        patterns: ["*"]
      npm-production:
        dependency-type: production
        patterns: ["*"]
    labels: [dependencies, npm]
    open-pull-requests-limit: 10
