import path from 'path';
import fs from 'fs';
import type { PRManager } from './pr-manager';
import type { BranchManager } from './branch-manager';
import type { VerificationManifest, ResidualRiskLedger } from '../verification/verification-manifest';
import type { RunResult } from '../scheduler/scheduler';

export interface RunPRLink {
  run_id: string;
  branch: string;
  pr_url: string | null;
  pr_number: number | null;
  status: 'pending' | 'open' | 'merged' | 'closed' | 'blocked';
  created_at: string;
  merged_at: string | null;
}

export interface PromotionOptions {
  baseBranch?: string;
  draftPR?: boolean;
  autoMerge?: boolean;
  mergeMethod?: 'merge' | 'squash' | 'rebase';
}

export type MergeGateVerdict = 'approved' | 'blocked' | 'needs_review';

export interface MergeGateReport {
  verdict: MergeGateVerdict;
  reasons: string[];
  blocking_risks: string[];
}

export class MergeGateEvaluator {
  evaluate(
    runResult: RunResult,
    manifest: VerificationManifest | null,
    riskLedger: ResidualRiskLedger | null
  ): MergeGateReport {
    const reasons: string[] = [];
    const blockingRisks: string[] = [];

    if (runResult.failed.length > 0) {
      reasons.push(`${runResult.failed.length} task(s) failed: ${runResult.failed.join(', ')}`);
    }

    if (runResult.blocked.length > 0) {
      reasons.push(`${runResult.blocked.length} task(s) blocked: ${runResult.blocked.join(', ')}`);
    }

    if (manifest && !manifest.summary.all_passed) {
      reasons.push(`Verification: ${manifest.summary.fail} check(s) failed, ${manifest.summary.error} error(s)`);
    }

    if (riskLedger) {
      const critical = riskLedger.risks.filter((r) => r.severity === 'critical' || r.severity === 'high');
      for (const risk of critical) {
        blockingRisks.push(`[${risk.severity.toUpperCase()}] ${risk.description}`);
      }
    }

    const hasBlockers = reasons.length > 0 || blockingRisks.length > 0;
    const verdict: MergeGateVerdict = hasBlockers ? 'blocked' : 'approved';

    return { verdict, reasons, blocking_risks: blockingRisks };
  }
}

export class PromotionPipeline {
  constructor(
    private readonly projectRoot: string,
    private readonly branchManager: BranchManager,
    private readonly prManager: PRManager,
    private readonly gateEvaluator: MergeGateEvaluator = new MergeGateEvaluator()
  ) {}

  buildPRBody(
    runResult: RunResult,
    manifest: VerificationManifest | null,
    riskLedger: ResidualRiskLedger | null
  ): string {
    const lines: string[] = [];
    lines.push('## OXE Run Summary');
    lines.push('');
    lines.push(`**Run ID:** \`${runResult.run_id}\``);
    lines.push(`**Status:** ${runResult.status}`);
    lines.push(`**Completed:** ${runResult.completed.length} tasks`);
    if (runResult.failed.length > 0) {
      lines.push(`**Failed:** ${runResult.failed.join(', ')}`);
    }
    if (runResult.blocked.length > 0) {
      lines.push(`**Blocked:** ${runResult.blocked.join(', ')}`);
    }

    if (manifest) {
      lines.push('');
      lines.push('## Verification');
      lines.push(`- Total: ${manifest.summary.total}`);
      lines.push(`- Pass: ${manifest.summary.pass}`);
      lines.push(`- Fail: ${manifest.summary.fail}`);
      lines.push(`- Skip: ${manifest.summary.skip}`);
    }

    if (riskLedger && riskLedger.risks.length > 0) {
      lines.push('');
      lines.push('## Residual Risks');
      for (const risk of riskLedger.risks) {
        lines.push(`- [${risk.severity.toUpperCase()}] ${risk.description}`);
        if (risk.mitigation) lines.push(`  - Mitigation: ${risk.mitigation}`);
      }
    }

    lines.push('');
    lines.push('---');
    lines.push('*Generated by OXE Runtime*');

    return lines.join('\n');
  }

  async promote(
    runResult: RunResult,
    manifest: VerificationManifest | null,
    riskLedger: ResidualRiskLedger | null,
    opts: PromotionOptions = {}
  ): Promise<RunPRLink> {
    const gateReport = this.gateEvaluator.evaluate(runResult, manifest, riskLedger);
    const link: RunPRLink = {
      run_id: runResult.run_id,
      branch: this.branchManager.currentBranch(),
      pr_url: null,
      pr_number: null,
      status: 'pending',
      created_at: new Date().toISOString(),
      merged_at: null,
    };

    if (gateReport.verdict === 'blocked') {
      link.status = 'blocked';
      this.savePRLink(runResult.run_id, link);
      return link;
    }

    const body = this.buildPRBody(runResult, manifest, riskLedger);
    const title = `oxe: run ${runResult.run_id} — ${runResult.completed.length} tasks`;

    const prResult = this.prManager.createDraft({
      title,
      body,
      base: opts.baseBranch ?? 'main',
      draft: opts.draftPR !== false,
    });

    if (!prResult.success || !prResult.url) {
      link.status = 'blocked';
      this.savePRLink(runResult.run_id, link);
      return link;
    }

    link.pr_url = prResult.url;
    link.status = 'open';
    this.savePRLink(runResult.run_id, link);

    return link;
  }

  savePRLink(runId: string, link: RunPRLink): void {
    const p = path.join(this.projectRoot, '.oxe', 'runs', runId, 'pr-link.json');
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, JSON.stringify(link, null, 2), 'utf8');
  }

  loadPRLink(runId: string): RunPRLink | null {
    const p = path.join(this.projectRoot, '.oxe', 'runs', runId, 'pr-link.json');
    if (!fs.existsSync(p)) return null;
    try {
      return JSON.parse(fs.readFileSync(p, 'utf8')) as RunPRLink;
    } catch {
      return null;
    }
  }
}
